<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-L24NCKJ" failures="1" tests="6" name="Test" time="0.188" errors="0" timestamp="2024-02-18T08:22:33 IST">
  <testcase classname="testng.listeners.UnknownFailureTest" name="unknownFail" time="0.033">
    <skipped/>
  </testcase> <!-- unknownFail -->
  <testcase classname="testng.listeners.UnknownFailureTest" name="unknownFail" time="0.002">
    <skipped/>
  </testcase> <!-- unknownFail -->
  <testcase classname="testng.listeners.UnknownFailureTest" name="unknownFail" time="0.003">
    <skipped/>
  </testcase> <!-- unknownFail -->
  <testcase classname="testng.listeners.UnknownFailureTest" name="unknownFail" time="0.003">
    <skipped/>
  </testcase> <!-- unknownFail -->
  <testcase classname="testng.listeners.UnknownFailureTest" name="unknownFail" time="0.006">
    <skipped/>
  </testcase> <!-- unknownFail -->
  <testcase classname="testng.listeners.UnknownFailureTest" name="unknownFail" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng.listeners.UnknownFailureTest.unknownFail(UnknownFailureTest.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- unknownFail -->
</testsuite> <!-- Test -->
